In [61]:
%pip install kagglehub

Collecting kagglehub
  Downloading kagglehub-1.0.2-py3-none-any.whl.metadata (40 kB)
Collecting kagglesdk<1.0,>=0.1.22 (from kagglehub)
  Downloading kagglesdk-0.1.37-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: packaging in c:\users\simra\anaconda3\lib\site-packages (from kagglehub) (25.0)
Requirement already satisfied: pyyaml in c:\users\simra\anaconda3\lib\site-packages (from kagglehub) (6.0.3)
Requirement already satisfied: requests in c:\users\simra\anaconda3\lib\site-packages (from kagglehub) (2.32.5)
Requirement already satisfied: tqdm in c:\users\simra\anaconda3\lib\site-packages (from kagglehub) (4.67.1)
Requirement already satisfied: protobuf in c:\users\simra\anaconda3\lib\site-packages (from kagglesdk<1.0,>=0.1.22->kagglehub) (5.29.3)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\simra\anaconda3\lib\site-packages (from requests->kagglehub) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\simra\anaconda3\lib\site-packages (from requests->kagglehub) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\simra\anaconda3\lib\site-packages (from requests->kagglehub) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\simra\anaconda3\lib\site-packages (from requests->kagglehub) (2025.11.12)
Requirement already satisfied: colorama in c:\users\simra\anaconda3\lib\site-packages (from tqdm->kagglehub) (0.4.6)
Downloading kagglehub-1.0.2-py3-none-any.whl (70 kB)
Downloading kagglesdk-0.1.37-py3-none-any.whl (262 kB)
Installing collected packages: kagglesdk, kagglehub

   ---------------------------------------- 0/2 [kagglesdk]
   ---------------------------------------- 0/2 [kagglesdk]
   ---------------------------------------- 0/2 [kagglesdk]
   ---------------------------------------- 0/2 [kagglesdk]
   ---------------------------------------- 0/2 [kagglesdk]
   ---------------------------------------- 0/2 [kagglesdk]
   ---------------------------------------- 0/2 [kagglesdk]
   ---------------------------------------- 0/2 [kagglesdk]
   ---------------------------------------- 0/2 [kagglesdk]
   ---------------------------------------- 0/2 [kagglesdk]
   ---------------------------------------- 0/2 [kagglesdk]
   ---------------------------------------- 0/2 [kagglesdk]
   -------------------- ------------------- 1/2 [kagglehub]
   -------------------- ------------------- 1/2 [kagglehub]
   -------------------- ------------------- 1/2 [kagglehub]
   ---------------------------------------- 2/2 [kagglehub]

Successfully installed kagglehub-1.0.2 kagglesdk-0.1.37
Note: you may need to restart the kernel to use updated packages.

In [64]:
import numpy as np
import pandas as pd
import kagglehub
import os

In [65]:
# movies = pd.read_csv('TMDB_all_movies.csv')

path = kagglehub.dataset_download("alanvourch/tmdb-movies-daily-updates")
movies = pd.read_csv(os.path.join(path, "TMDB_all_movies.csv"))

In [66]:
pd.set_option('display.max_column', None)
movies.head(1)

,id,title,vote_average,vote_count,status,release_date,revenue,runtime,budget,imdb_id,original_language,original_title,overview,popularity,tagline,genres,production_companies,production_countries,spoken_languages,cast,director,director_of_photography,writers,producers,music_composer,imdb_rating,imdb_votes,poster_path,keywords,certification_us
0,2,Ariel,7.118,380.0,Released,1988-10-21,0.0,73.0,0.0,tt0094675,fi,Ariel,A Finnish man goes to the city to find a job a...,3.2803,NaN,"Comedy, Drama, Romance, Crime",Villealfa Filmproductions,Finland,suomi,"Turo Pajala, Susanna Haavisto, Matti Pellonpää...",Aki Kaurismäki,Timo Salminen,Aki Kaurismäki,Aki Kaurismäki,NaN,7.4,9983.0,/ojDg0PGvs6R9xYFodRct2kdI6wC.jpg,"prison|underdog|helsinki, finland|factory work...",NaN

In [67]:
movies.shape

(1234647, 30)

In [68]:
movies.columns.tolist()

['id',
 'title',
 'vote_average',
 'vote_count',
 'status',
 'release_date',
 'revenue',
 'runtime',
 'budget',
 'imdb_id',
 'original_language',
 'original_title',
 'overview',
 'popularity',
 'tagline',
 'genres',
 'production_companies',
 'production_countries',
 'spoken_languages',
 'cast',
 'director',
 'director_of_photography',
 'writers',
 'producers',
 'music_composer',
 'imdb_rating',
 'imdb_votes',
 'poster_path',
 'keywords',
 'certification_us']

In [69]:
movies.head(1)

,id,title,vote_average,vote_count,status,release_date,revenue,runtime,budget,imdb_id,original_language,original_title,overview,popularity,tagline,genres,production_companies,production_countries,spoken_languages,cast,director,director_of_photography,writers,producers,music_composer,imdb_rating,imdb_votes,poster_path,keywords,certification_us
0,2,Ariel,7.118,380.0,Released,1988-10-21,0.0,73.0,0.0,tt0094675,fi,Ariel,A Finnish man goes to the city to find a job a...,3.2803,NaN,"Comedy, Drama, Romance, Crime",Villealfa Filmproductions,Finland,suomi,"Turo Pajala, Susanna Haavisto, Matti Pellonpää...",Aki Kaurismäki,Timo Salminen,Aki Kaurismäki,Aki Kaurismäki,NaN,7.4,9983.0,/ojDg0PGvs6R9xYFodRct2kdI6wC.jpg,"prison|underdog|helsinki, finland|factory work...",NaN

In [70]:
movies.head(1)["cast"].values

array(['Turo Pajala, Susanna Haavisto, Matti Pellonpää, Eetu Hilkamo, Erkki Pajala, Matti Jaaranen, Hannu Viholainen, Jorma Markkula, Tarja Keinänen, Eino Kuusela, Kauko Laalo, Jyrki Olsonen, Esko Nikkari, Marja Packalén, Mikko Remes, Tomi Salmela, Reijo Marin, Heikki Salomaa, Veikko Uusimäki, Esko Salminen, Hannu Kivisalo, Pekka Wilen, Heikki Anttila, Pentti Auer, Timo Harakka, Kari Helaseppä, Juuso Hirvikangas, Hanna Jokinen, Sakari Kuosmanen, Sami Lanki, Jouko Lumme, Mikko Lyytikäinen, Timo Markko, Merja Pulkkinen, Markku Rantala, Sirkka Rautiainen, Jaakko Talaskivi, Timo Toikka, Olli Varja'],
      dtype=object)

In [71]:
movies['spoken_languages'].value_counts()

spoken_languages
English                                       246948
Español                                        51451
日本語                                            49338
No Language                                    47206
Français                                       45975
                                               ...
, English, български език, , Türkçe                1
普通话, English, हिन्दी, Bahasa melayu                1
Íslenska, English, svenska                         1
Pусский, Deutsch, English, فارسی, Français         1
Hrvatski, हिन्दी, English                          1
Name: count, Length: 8063, dtype: int64

In [72]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1234647 entries, 0 to 1234646
Data columns (total 30 columns):
 #   Column                   Non-Null Count    Dtype
---  ------                   --------------    -----
 0   id                       1234647 non-null  int64
 1   title                    1234632 non-null  object
 2   vote_average             1234647 non-null  float64
 3   vote_count               1234647 non-null  float64
 4   status                   1234647 non-null  object
 5   release_date             1102971 non-null  object
 6   revenue                  1234647 non-null  float64
 7   runtime                  1234647 non-null  float64
 8   budget                   1234647 non-null  float64
 9   imdb_id                  682084 non-null   object
 10  original_language        1234647 non-null  object
 11  original_title           1234633 non-null  object
 12  overview                 1044858 non-null  object
 13  popularity               1234647 non-null  float64
 14  tagline                  189303 non-null   object
 15  genres                   902566 non-null   object
 16  production_companies     596880 non-null   object
 17  production_countries     775923 non-null   object
 18  spoken_languages         783677 non-null   object
 19  cast                     844316 non-null   object
 20  director                 1036573 non-null  object
 21  director_of_photography  336839 non-null   object
 22  writers                  626151 non-null   object
 23  producers                425587 non-null   object
 24  music_composer           142293 non-null   object
 25  imdb_rating              477494 non-null   float64
 26  imdb_votes               477494 non-null   float64
 27  poster_path              934809 non-null   object
 28  keywords                 349262 non-null   object
 29  certification_us         92734 non-null    object
dtypes: float64(8), int64(1), object(21)
memory usage: 282.6+ MB

In [73]:
# title
# release_date
# imdb_id
# overview
# genres
# spoken_languages
# cast
# director
# keywords
# popularity

movies = movies[['title', 'release_date', 'imdb_id', 'overview', 'spoken_languages', 'cast', 'director', 'keywords', 'popularity']]

In [74]:
movies.head(1)

,title,release_date,imdb_id,overview,spoken_languages,cast,director,keywords,popularity
0,Ariel,1988-10-21,tt0094675,A Finnish man goes to the city to find a job a...,suomi,"Turo Pajala, Susanna Haavisto, Matti Pellonpää...",Aki Kaurismäki,"prison|underdog|helsinki, finland|factory work...",3.2803

In [75]:
movies.isnull().sum()

title                   15
release_date        131676
imdb_id             552563
overview            189789
spoken_languages    450970
cast                390331
director            198074
keywords            885385
popularity               0
dtype: int64

In [76]:
movies = movies.dropna(subset=['imdb_id'])

In [77]:
movies.duplicated().sum()

np.int64(0)

In [78]:
movies['spoken_languages'] = movies['spoken_languages'].fillna('Unknown')

In [79]:
movies['keywords'] = movies['keywords'].fillna('Unknown')
movies['cast'] = movies['cast'].fillna('Unknown')
movies['director'] = movies['director'].fillna('Unknown')
movies['overview'] = movies['overview'].fillna('Unknown')

In [80]:
movies = movies.dropna(subset=['title'])

In [81]:
movies['release_date'] = pd.to_datetime(movies['release_date'] , errors = 'coerce')

In [82]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
Index: 682080 entries, 0 to 1234643
Data columns (total 9 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   title             682080 non-null  object
 1   release_date      648057 non-null  datetime64[ns]
 2   imdb_id           682080 non-null  object
 3   overview          682080 non-null  object
 4   spoken_languages  682080 non-null  object
 5   cast              682080 non-null  object
 6   director          682080 non-null  object
 7   keywords          682080 non-null  object
 8   popularity        682080 non-null  float64
dtypes: datetime64[ns](1), float64(1), object(7)
memory usage: 52.0+ MB

In [83]:
movies.head(1)

,title,release_date,imdb_id,overview,spoken_languages,cast,director,keywords,popularity
0,Ariel,1988-10-21,tt0094675,A Finnish man goes to the city to find a job a...,suomi,"Turo Pajala, Susanna Haavisto, Matti Pellonpää...",Aki Kaurismäki,"prison|underdog|helsinki, finland|factory work...",3.2803

In [84]:
movies['overview'] = movies['overview'].apply(lambda x: x.split())

In [85]:
movies['spoken_languages'] = movies['spoken_languages'].apply(lambda x: x.split(','))
movies['cast'] = movies['cast'].apply(lambda x: x.split(','))
movies['keywords'] = movies['keywords'].apply(lambda x: x.split('|'))

In [86]:
movies.head(1)

,title,release_date,imdb_id,overview,spoken_languages,cast,director,keywords,popularity
0,Ariel,1988-10-21,tt0094675,"[A, Finnish, man, goes, to, the, city, to, fin...",[suomi],"[Turo Pajala, Susanna Haavisto, Matti Pellon...",Aki Kaurismäki,"[prison, underdog, helsinki, finland, factory ...",3.2803

In [91]:
movies['release_year'] = movies['release_date'].dt.year.astype('Int64')
movies = movies[['title', 'release_year', 'imdb_id', 'overview', 'spoken_languages', 'cast', 'director', 'keywords']]

In [92]:
movies['cast'] = movies['cast'].apply(lambda x: [i.replace(" ", "") for i in x])

In [93]:
movies['director'].str.replace(" ", "")

0                                              AkiKaurismäki
1                                              AkiKaurismäki
2          QuentinTarantino,RobertRodriguez,AlexandreRock...
3                                             StephenHopkins
4                                                TimoNovotny
                                 ...
1234637                                      SatoruKobayashi
1234638                                              Unknown
1234639                                      SatoruKobayashi
1234640                                              Unknown
1234643                                              Unknown
Name: director, Length: 682080, dtype: object

In [94]:
movies['director'] = movies['director'].apply(lambda x: x.split(','))

In [95]:
movies.head(1)

,title,release_year,imdb_id,overview,spoken_languages,cast,director,keywords
0,Ariel,1988,tt0094675,"[A, Finnish, man, goes, to, the, city, to, fin...",[suomi],"[TuroPajala, SusannaHaavisto, MattiPellonpää, ...",[Aki Kaurismäki],"[prison, underdog, helsinki, finland, factory ..."

In [96]:
movies['director'] = movies['director'].apply(lambda x: [i.replace(" ", "") for i in x])
movies['keywords'] = movies['keywords'].apply(lambda x: [i.replace(" ", "") for i in x])

In [97]:
movies['spoken_languages'] = movies['spoken_languages'].apply(lambda x: [i.replace(" ", "") for i in x])

In [98]:
movies['tags'] = movies['overview'] + movies['spoken_languages'] + movies['cast'] + movies['director'] + movies['keywords']

In [99]:
movies_clean = movies[['title', 'imdb_id', 'tags']]

In [100]:
movies_clean.head(1)

   title    imdb_id                                               tags
0  Ariel  tt0094675  [A, Finnish, man, goes, to, the, city, to, fin...

In [101]:
movies_clean['tags'] = movies_clean['tags'].apply(lambda x:" ".join(x))

C:\Users\simra\AppData\Local\Temp\ipykernel_30684\2328421068.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies_clean['tags'] = movies_clean['tags'].apply(lambda x:" ".join(x))

In [102]:
movies_clean['tags'][0]

'A Finnish man goes to the city to find a job after the mine where he worked is closed and his father commits suicide. suomi TuroPajala SusannaHaavisto MattiPellonpää EetuHilkamo ErkkiPajala MattiJaaranen HannuViholainen JormaMarkkula TarjaKeinänen EinoKuusela KaukoLaalo JyrkiOlsonen EskoNikkari MarjaPackalén MikkoRemes TomiSalmela ReijoMarin HeikkiSalomaa VeikkoUusimäki EskoSalminen HannuKivisalo PekkaWilen HeikkiAnttila PenttiAuer TimoHarakka KariHelaseppä JuusoHirvikangas HannaJokinen SakariKuosmanen SamiLanki JoukoLumme MikkoLyytikäinen TimoMarkko MerjaPulkkinen MarkkuRantala SirkkaRautiainen JaakkoTalaskivi TimoToikka OlliVarja AkiKaurismäki prison underdog helsinki,finland factoryworker prisoner fallinginlove'

In [103]:
movies_clean['tags'] = movies_clean['tags'].apply(lambda x: x.lower())

C:\Users\simra\AppData\Local\Temp\ipykernel_30684\2361322775.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies_clean['tags'] = movies_clean['tags'].apply(lambda x: x.lower())

In [104]:
movies_clean.head()

,title,imdb_id,tags
0,Ariel,tt0094675,a finnish man goes to the city to find a job a...
1,Shadows in Paradise,tt0092149,"nikander, a rubbish collector and would-be ent..."
2,Four Rooms,tt0113101,it's ted the bellhop's first night on the job....
3,Judgment Night,tt0107286,"four young friends, while taking a shortcut en..."
4,Life in Loops (A Megacities RMX),tt0825671,timo novotny labels his new project an experim...

In [105]:
movies_clean['tags'] = movies_clean['tags'].str.replace('Unknown','')

C:\Users\simra\AppData\Local\Temp\ipykernel_30684\4172092555.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies_clean['tags'] = movies_clean['tags'].str.replace('Unknown','')

In [106]:
# Now, we will do text vectorization

In [107]:
from sklearn.feature_extraction.text import CountVectorizer

In [110]:
cv = CountVectorizer(max_features = 10000, stop_words='english', min_df=5)

In [111]:
vectors = cv.fit_transform(movies_clean['tags'])

In [112]:
len(cv.get_feature_names_out())

10000

In [115]:
vectors[0].toarray()

array([[0, 0, 0, ..., 0, 0, 0]], shape=(1, 10000))